// AUTO-GENERATED by `npm run bundle:functions` — do not edit directly.
// Edit src.ts (or ../_shared/telegram.ts) instead, then re-run the bundler.


// supabase/functions/telegram-auth/src.ts
import { createClient } from "npm:@supabase/supabase-js@2";

// supabase/functions/_shared/telegram.ts
var MAX_AUTH_AGE_SECONDS = 24 * 60 * 60;
async function hmacSha256(key, message) {
  const cryptoKey = await crypto.subtle.importKey(
    "raw",
    key,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  return crypto.subtle.sign("HMAC", cryptoKey, new TextEncoder().encode(message));
}
function toHex(buffer) {
  return Array.from(new Uint8Array(buffer)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
async function verifyTelegramInitData(initData, botToken) {
  const params = new URLSearchParams(initData);
  const hash = params.get("hash");
  if (!hash) return null;
  params.delete("hash");
  const authDate = params.get("auth_date");
  if (!authDate) return null;
  const ageSeconds = Math.floor(Date.now() / 1e3) - Number(authDate);
  if (ageSeconds > MAX_AUTH_AGE_SECONDS || ageSeconds < 0) return null;
  const dataCheckString = Array.from(params.entries()).sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => `${key}=${value}`).join("\n");
  const secretKey = await hmacSha256(new TextEncoder().encode("WebAppData"), botToken);
  const computedHash = toHex(await hmacSha256(secretKey, dataCheckString));
  if (computedHash !== hash) return null;
  const userRaw = params.get("user");
  if (!userRaw) return null;
  return { user: JSON.parse(userRaw) };
}
var corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type"
};

// supabase/functions/telegram-auth/src.ts
var BOT_TOKEN = Deno.env.get("TELEGRAM_BOT_TOKEN");
var SUPABASE_URL = Deno.env.get("SUPABASE_URL");
var SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }
  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405, headers: corsHeaders });
  }
  const { initData } = await req.json().catch(() => ({}));
  if (typeof initData !== "string") {
    return new Response(JSON.stringify({ error: "initData required" }), {
      status: 400,
      headers: { ...corsHeaders, "Content-Type": "application/json" }
    });
  }
  const verified = await verifyTelegramInitData(initData, BOT_TOKEN);
  if (!verified) {
    return new Response(JSON.stringify({ error: "invalid initData" }), {
      status: 401,
      headers: { ...corsHeaders, "Content-Type": "application/json" }
    });
  }
  const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);
  const { data: player, error: playerError } = await supabase.from("players").upsert(
    { telegram_id: verified.user.id, username: verified.user.username ?? null },
    { onConflict: "telegram_id" }
  ).select().single();
  if (playerError) {
    return new Response(JSON.stringify({ error: playerError.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" }
    });
  }
  const { data: claimedOnboarding } = await supabase.from("players").update({ onboarded: true }).eq("id", player.id).eq("onboarded", false).select().maybeSingle();
  if (claimedOnboarding) {
    await supabase.from("workers").insert(
      Array.from({ length: 4 }, (_, i) => ({ player_id: player.id, position: i }))
    );
    const reserve = Math.floor(500 + Math.random() * 1500);
    await supabase.from("oil_fields").insert({
      owner_id: player.id,
      reserve_total: reserve,
      reserve_remaining: reserve
    });
    await supabase.from("refineries").insert({ owner_id: player.id });
    await supabase.from("transports").insert({ owner_id: player.id });
    await supabase.from("parts_factories").insert({ owner_id: player.id });
  }
  return new Response(JSON.stringify({ player }), {
    headers: { ...corsHeaders, "Content-Type": "application/json" }
  });
});
